apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: image
global:
  registry: private-registry:5000

charts:
- name: glance
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      bootstrap: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_drop: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_init: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      glance_api: $(registry)/stein/ubuntu-source-glance-api:taco-0.1.0
      glance_db_sync: $(registry)/stein/ubuntu-source-glance-api:taco-0.1.0
      glance_metadefs_load: $(registry)/stein/ubuntu-source-glance-api:taco-0.1.0
      glance_registry: $(registry)/stein/ubuntu-source-glance-registry:taco-0.1.0
      glance_storage_init: $(registry)/port/ceph-config-helper:v1.14.3
      image_repo_sync: $(registry)/docker:17.07.0
      ks_endpoints: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_service: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_user: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      rabbit_init: $(registry)/rabbitmq:3.7-management
      test: $(registry)/stein/ubuntu-source-rally:taco-0.1.0

- name: heat
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      bootstrap: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_drop: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_init: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      heat_api: $(registry)/stein/ubuntu-source-heat-api:taco-0.1.0
      heat_cfn: $(registry)/stein/ubuntu-source-heat-api:taco-0.1.0
      heat_cloudwatch: $(registry)/stein/ubuntu-source-heat-api:taco-0.1.0
      heat_db_sync: $(registry)/stein/ubuntu-source-heat-api:taco-0.1.0
      heat_engine: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      heat_engine_cleaner: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      heat_purge_deleted: $(registry)/openstackhelm/heat:ocata-ubuntu_xenial
      image_repo_sync: $(registry)/docker:17.07.0
      ks_endpoints: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_service: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_user: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      rabbit_init: $(registry)/rabbitmq:3.7-management
      test: $(registry)/stein/ubuntu-source-rally:taco-0.1.0
 
- name: horizon
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      db_drop: $(registry)/stein/ubuntu-source-horizon:taco-0.1.0
      db_init: $(registry)/stein/ubuntu-source-horizon:taco-0.1.0
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      horizon: $(registry)/stein/ubuntu-source-horizon:taco-0.1.0
      horizon_db_sync: $(registry)/stein/ubuntu-source-horizon:taco-0.1.0
      image_repo_sync: $(registry)/docker:17.07.0
      test: $(registry)/openstackhelm/osh-selenium:latest-ubuntu_bionic

- name: ingress
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      entrypoint: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      error_pages: $(registry)/google_containers/defaultbackend:1.0
      image_repo_sync: $(registry)/docker:17.07.0
      ingress: $(registry)/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0
      ingress_module_init: $(registry)/stein/ubuntu-source-neutron-server:taco-0.1.0
      ingress_routed_vip: $(registry)/stein/ubuntu-source-neutron-server:taco-0.1.0
      keepalived: $(registry)/osixia/keepalived:1.4.5

- name: keystone
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      bootstrap: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_drop: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_init: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      image_repo_sync: $(registry)/docker:17.07.0
      keystone_api: $(registry)/stein/ubuntu-source-keystone:taco-0.1.0
      keystone_credential_cleanup: $(registry)/openstackhelm/heat:ocata-ubuntu_xenial
      keystone_credential_rotate: $(registry)/stein/ubuntu-source-keystone:taco-0.1.0
      keystone_credential_setup: $(registry)/stein/ubuntu-source-keystone:taco-0.1.0
      keystone_db_sync: $(registry)/stein/ubuntu-source-keystone:taco-0.1.0
      keystone_domain_manage: $(registry)/stein/ubuntu-source-keystone:taco-0.1.0
      keystone_fernet_rotate: $(registry)/stein/ubuntu-source-keystone:taco-0.1.0
      keystone_fernet_setup: $(registry)/stein/ubuntu-source-keystone:taco-0.1.0
      ks_user: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      rabbit_init: $(registry)/rabbitmq:3.7-management
      test: $(registry)/stein/ubuntu-source-rally:taco-0.1.0

- name: libvirt
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      image_repo_sync: $(registry)/docker:17.07.0
      libvirt: $(registry)/stein/ubuntu-source-nova-libvirt:taco-0.1.0

- name: mariadb
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      error_pages: $(registry)/google_containers/defaultbackend:1.0
      image_repo_sync: $(registry)/docker:17.07.0
      ingress: $(registry)/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
      mariadb: $(registry)/openstackhelm/mariadb:10.2.18
      mariadb_backup: $(registry)/openstackhelm/mariadb:latest-ubuntu_xenial
      prometheus_create_mysql_user: $(registry)/mariadb:10.2.13
      prometheus_mysql_exporter: $(registry)/prom/mysqld-exporter:v0.10.0
      prometheus_mysql_exporter_helm_tests: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      scripted_test: $(registry)/openstackhelm/mariadb:latest-ubuntu_xenial

- name: memcached
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      image_repo_sync: $(registry)/docker:17.07.0
      memcached: $(registry)/memcached:1.5.5
      prometheus_memcached_exporter: $(registry)/prom/memcached-exporter:v0.4.1

- name: neutron
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      bootstrap: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_drop: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_init: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      image_repo_sync: $(registry)/docker:17.07.0
      ks_endpoints: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_service: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_user: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      neutron_bagpipe_bgp: $(registry)/stein/ubuntu-source-neutron-server:taco-0.1.0
      neutron_db_sync: $(registry)/stein/ubuntu-source-neutron-server:taco-0.1.0
      neutron_dhcp: $(registry)/stein/ubuntu-source-neutron-dhcp-agent:taco-0.1.0
      neutron_ironic_agent: $(registry)/stein/ubuntu-source-neutron-server:taco-0.1.0
      neutron_l2gw: $(registry)/stein/ubuntu-source-neutron-server:taco-0.1.0
      neutron_l3: $(registry)/stein/ubuntu-source-neutron-l3-agent:taco-0.1.0
      neutron_linuxbridge_agent: $(registry)/stein/ubuntu-source-neutron-linuxbridge-agent:taco-0.1.0
      neutron_metadata: $(registry)/stein/ubuntu-source-neutron-metadata-agent:taco-0.1.0
      neutron_openvswitch_agent: $(registry)/stein/ubuntu-source-neutron-openvswitch-agent:taco-0.1.0
      neutron_server: $(registry)/stein/ubuntu-source-neutron-server:taco-0.1.0.onos
      neutron_sriov_agent: $(registry)/stein/ubuntu-source-neutron-sriov-agent:taco-0.1.0
      neutron_sriov_agent_init: $(registry)/stein/ubuntu-source-neutron-sriov-agent:taco-0.1.0
      purge_test: $(registry)/openstackhelm/ospurge:latest
      rabbit_init: $(registry)/rabbitmq:3.7-management
      test: $(registry)/xrally/xrally-openstack:1.5.0

- name: nova
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      bootstrap: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_drop: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_init: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      image_repo_sync: $(registry)/docker:17.07.0
      ks_endpoints: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_service: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_user: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      nova_api: $(registry)/stein/ubuntu-source-nova-api:taco-0.1.0
      nova_cell_setup: $(registry)/stein/ubuntu-source-nova-api:taco-0.1.0
      nova_cell_setup_init: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      nova_compute: $(registry)/stein/ubuntu-source-nova-compute:taco-0.1.0
      nova_compute_ironic: $(registry)/stein/ubuntu-source-nova-compute-ironic:taco-0.1.0
      nova_compute_ssh: $(registry)/stein/ubuntu-source-nova-ssh:taco-0.1.0
      nova_conductor: $(registry)/stein/ubuntu-source-nova-conductor:taco-0.1.0
      nova_consoleauth: $(registry)/stein/ubuntu-source-nova-consoleauth:taco-0.1.0
      nova_db_sync: $(registry)/stein/ubuntu-source-nova-api:taco-0.1.0
      nova_novncproxy: $(registry)/stein/ubuntu-source-nova-novncproxy:taco-0.1.0
      nova_novncproxy_assets: $(registry)/stein/ubuntu-source-nova-novncproxy:taco-0.1.0
      nova_placement: $(registry)/stein/ubuntu-source-nova-placement-api:taco-0.1.0
      nova_scheduler: $(registry)/stein/ubuntu-source-nova-scheduler:taco-0.1.0
      nova_service_cleaner: $(registry)/port/ceph-config-helper:v1.14.3
      nova_spiceproxy: $(registry)/stein/ubuntu-source-nova-spicehtml5proxy:taco-0.1.0
      nova_spiceproxy_assets: $(registry)/stein/ubuntu-source-nova-spicehtml5proxy:taco-0.1.0
      rabbit_init: $(registry)/rabbitmq:3.7-management
      test: $(registry)/stein/ubuntu-source-rally:taco-0.1.0

- name: prometheus-openstack-exporter
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      image_repo_sync: $(registry)/docker:17.07.0
      ks_user: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      prometheus_openstack_exporter: $(registry)/openstackhelm/prometheus-openstack-exporter:ubuntu_bionic-20191017

- name: rabbitmq
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      image_repo_sync: $(registry)/docker:17.07.0
      prometheus_rabbitmq_exporter: $(registry)/kbudde/rabbitmq-exporter:v0.21.0
      prometheus_rabbitmq_exporter_helm_tests: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      rabbitmq: $(registry)/rabbitmq:3.7.13
      rabbitmq_init: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      scripted_test: $(registry)/rabbitmq:3.7.13-management

- name: ceph-provisioners
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      ceph_bootstrap: $(registry)/openstackhelm/ceph-daemon:latest-ubuntu_xenial
      ceph_cephfs_provisioner: $(registry)/openstackhelm/ceph-cephfs-provisioner:latest-ubuntu_xenial
      ceph_config_helper: $(registry)/port/ceph-config-helper:v1.14.3
      ceph_rbd_provisioner: $(registry)/openstackhelm/ceph-rbd-provisioner:latest-ubuntu_xenial
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      image_repo_sync: $(registry)/docker:17.07.0

- name: cinder
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      bootstrap: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      cinder_api: $(registry)/stein/ubuntu-source-cinder-api:taco-0.1.0
      cinder_backup: $(registry)/stein/ubuntu-source-cinder-backup:taco-0.1.0
      cinder_backup_storage_init: $(registry)/port/ceph-config-helper:v1.14.3
      cinder_db_sync: $(registry)/stein/ubuntu-source-cinder-api:taco-0.1.0
      cinder_scheduler: $(registry)/stein/ubuntu-source-cinder-scheduler:taco-0.1.0
      cinder_storage_init: $(registry)/port/ceph-config-helper:v1.14.3
      cinder_volume: $(registry)/stein/ubuntu-source-cinder-volume:taco-0.1.0
      cinder_volume_usage_audit: $(registry)/stein/ubuntu-source-cinder-volume:taco-0.1.0
      db_drop: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_init: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      image_repo_sync: $(registry)/docker:17.07.0
      ks_endpoints: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_service: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_user: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      rabbit_init: $(registry)/rabbitmq:3.7-management
      test: $(registry)/xrally/xrally-openstack:1.5.0

- name: ironic
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      bootstrap: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_drop: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      db_init: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
      image_repo_sync: $(registry)/docker:17.07.0
      ironic_api: $(registry)/stein/ubuntu-source-ironic-api:taco-0.1.0
      ironic_conductor: $(registry)/stein/ubuntu-source-ironic-conductor:taco-0.1.0
      ironic_db_sync: $(registry)/stein/ubuntu-source-ironic-api:taco-0.1.0
      ironic_manage_cleaning_network: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ironic_pxe: $(registry)/stein/ubuntu-source-ironic-pxe:taco-0.1.0
      ironic_pxe_http: $(registry)/nginx:1.13.3
      ironic_pxe_init: $(registry)/stein/ubuntu-source-ironic-pxe:taco-0.1.0
      ironic_retrive_cleaning_network: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ironic_retrive_swift_config: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_endpoints: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_service: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      ks_user: $(registry)/stein/ubuntu-source-heat-engine:taco-0.1.0
      rabbit_init: $(registry)/rabbitmq:3.7-management

- name: sona
  override:
    images.pull_policy: IfNotPresent
    images.tags:
      curl: $(registry)/os-client-docker:latest
      onos: $(registry)/onos-sona-nightly-docker:stable
      python: $(registry)/python:2-alpine

