apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: image
global:
  registry: private-registry:5000

charts:
- name: eck-resource
  override:
    elasticsearch.image.repository: $(registry)/elasticsearch/elasticsearch
    elasticsearch.image.tag: 7.5.1
    kibana.image.repository: $(registry)/kibana/kibana
    kibana.image.tag: 7.5.1

- name: eck-operator
  override:
    image.repository: docker.elastic.co/eck/eck-operator
    image.tag: null

- name: addons
  override:
    kibanaInit.image.repository: $(registry)/kibana-init
    kibanaInit.image.tag: v4
    metricbeat.image.repository: $(registry)/metricbeat
    metricbeat.image.tag: taco-1.0.0

- name: fed-addons
  override:
    kibanaInit.image.repository: $(registry)/kibana-init
    kibanaInit.image.tag: v4
    metricbeat.image.repository: $(registry)/metricbeat
    metricbeat.image.tag: taco-1.0.0

- name: fluentbit
  override:
    image.exporter.repository: $(registry)/logalert-exporter
    image.exporter.tag: v0.1.1
    image.fluentbit.repository: $(registry)/fluent-bit-for-operator
    image.fluentbit.tag: v1.4.6
    image.hyperkube.repository: $(registry)/hyperkube
    image.hyperkube.tag: v1.17.6
    image.init.repository: $(registry)/library/docker
    image.init.tag: 19.03
    image.operator.repository: $(registry)/fluentbit-operator
    image.operator.tag: v0.1.1
    image.elasticsearchTemplates.repository: $(registry)/openstackhelm/heat
    image.elasticsearchTemplates.tag: newton

- name: fluentbit-operator
  override:
    image.exporter.repository: $(registry)/logalert-exporter
    image.exporter.tag: v0.1.1
    image.fluentbit.repository: $(registry)/fluent-bit-for-operator
    image.fluentbit.tag: v1.4.6
    image.hyperkube.repository: $(registry)/hyperkube
    image.hyperkube.tag: v1.17.6
    image.init.repository: $(registry)/library/docker
    image.init.tag: 19.03
    image.operator.repository: $(registry)/fluentbit-operator
    image.operator.tag: v0.1.1
    image.elasticsearchTemplates.repository: $(registry)/openstackhelm/heat
    image.elasticsearchTemplates.tag: newton

- name: grafana
  override:
    downloadDashboardsImage.repository: $(registry)/curl
    downloadDashboardsImage.tag: 7.70.0
    image.repository: $(registry)/grafana
    image.tag: 7.1.1
    initChownData.image.repository: $(registry)/library/busybox
    initChownData.image.tag: 1.31.1
    sidecar.image.repository: $(registry)/k8s-sidecar
    sidecar.image.tag: 0.1.151
    testFramework.image: $(registry)/bats
    testFramework.tag: v1.1.0

- name: kube-state-metrics
  override:
    image.repository: $(registry)/bitnami/kube-state-metrics
    image.tag: 1.9.7-debian-10-r143

- name: prometheus
  override:
    alertmanager.alertmanagerSpec.image.repository: $(registry)/prometheus/alertmanager
    alertmanager.alertmanagerSpec.image.tag: v0.21.0
    prometheusOperator.admissionWebhooks.patch.image.repository: $(registry)/kube-webhook-certgen
    prometheusOperator.admissionWebhooks.patch.image.tag: v1.5.0
    prometheusOperator.image.repository: $(registry)/prometheus-operator/prometheus-operator
    prometheusOperator.image.tag: v0.46.0
    prometheusOperator.prometheusConfigReloaderImage.repository: $(registry)/prometheus-operator/prometheus-config-reloader
    prometheusOperator.prometheusConfigReloaderImage.tag: v0.46.0
    prometheus.prometheusSpec.image.repository: $(registry)/prometheus/prometheus
    prometheus.prometheusSpec.image.tag: v2.24.0

- name: prometheus-adapter
  override:
    image.repository: $(registry)/k8s-prometheus-adapter-amd64
    image.tag: v0.7.0

- name: prometheus-fed-master
  override:
    alertmanager.alertmanagerSpec.image.repository: $(registry)/prometheus/alertmanager
    alertmanager.alertmanagerSpec.image.tag: v0.21.0
    prometheusOperator.admissionWebhooks.patch.image.repository: $(registry)/kube-webhook-certgen
    prometheusOperator.admissionWebhooks.patch.image.tag: v1.5.0
    prometheusOperator.image.repository: $(registry)/prometheus-operator/prometheus-operator
    prometheusOperator.image.tag: v0.46.0
    prometheusOperator.prometheusConfigReloaderImage.repository: $(registry)/prometheus-operator/prometheus-config-reloader
    prometheusOperator.prometheusConfigReloaderImage.tag: v0.46.0
    prometheus.prometheusSpec.image.repository: $(registry)/prometheus/prometheus
    prometheus.prometheusSpec.image.tag: v2.24.0

- name: prometheus-node-exporter
  override:
    image.repository: $(registry)/prometheus/node-exporter
    image.tag: v1.0.1

- name: prometheus-operator
  override:
    alertmanager.alertmanagerSpec.image.repository: $(registry)/prometheus/alertmanager
    alertmanager.alertmanagerSpec.image.tag: v0.21.0
    prometheusOperator.admissionWebhooks.patch.image.repository: $(registry)/kube-webhook-certgen
    prometheusOperator.admissionWebhooks.patch.image.tag: v1.5.0
    prometheusOperator.image.repository: $(registry)/prometheus-operator/prometheus-operator
    prometheusOperator.image.tag: v0.46.0
    prometheusOperator.prometheusConfigReloaderImage.repository: $(registry)/prometheus-operator/prometheus-config-reloader
    prometheusOperator.prometheusConfigReloaderImage.tag: v0.46.0
    prometheus.prometheusSpec.image.repository: $(registry)/prometheus/prometheus
    prometheus.prometheusSpec.image.tag: v2.24.0

- name: prometheus-process-exporter
  override:
    images.tags.dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
    images.tags.image_repo_sync: $(registry)/library/docker:17.07.0
    images.tags.process_exporter: $(registry)/process-exporter:0.2.11

- name: prometheus-pushgateway
  override:
    image.repository: $(registry)/pushgateway
    image.tag: v1.3.0

- name: kubernetes-event-exporter
  override:
    image.repository: $(registry)/siim/kubernetes-event-exporter
    image.tag: 0.1.0
    image.PullPolicy: IfNotPresent

- name: thanos
  override:
    image.registry: $(registry)
    image.repository: bitnami/thanos
    image.tag: 0.17.2-scratch-r1
    volumePermissions.image.registry: $(registry)
    volumePermissions.image.repository: bitnami/minideb
    volumePermissions.image.tag: buster
    minio.image.registry: $(registry)
    minio.image.repository: bitnami/minio
    minio.image.tag: 2021.2.14-debian-10-r0
    minio.clientImage.registry: $(registry)
    minio.clientImage.repository: bitnami/minio-client
    minio.clientImage.tag: 2021.2.14-debian-10-r0
    minio.volumePermissions.image.registry: $(registry)
    minio.volumePermissions.image.repository: bitnami/minideb
    minio.volumePermissions.image.tag: buster

- name: thanos-config
  override: {}

- name: prepare-etcd-secret
  override:
    image.repository: $(registry)/hyperkube
    image.tag: v1.18.8
